SELECT 
  * 
FROM
  VG_INSTANCE_DATA_VG_CTY_MID_DUMMY 
WHERE (
    CASE
      WHEN Dummy IS NULL 
      AND DATETIME_ROW_START IS NULL 
      THEN 1 
      WHEN Dummy IS NULL 
      AND DATETIME_ROW_START IS NOT NULL 
      THEN 0 
      WHEN Dummy IS NOT NULL 
      AND DATETIME_ROW_START IS NULL 
      THEN 1 
      ELSE Dummy <= DATETIME_ROW_START 
    END
  ) 
  AND (
    CASE
      WHEN DATETIME_ROW_START IS NULL 
      AND DATETIME_ROW_END IS NULL 
      THEN 1 
      WHEN DATETIME_ROW_START IS NULL 
      AND DATETIME_ROW_END IS NOT NULL 
      THEN 0 
      WHEN DATETIME_ROW_START IS NOT NULL 
      AND DATETIME_ROW_END IS NULL 
      THEN 1 
      ELSE DATETIME_ROW_START <= DATETIME_ROW_END 
    END
  ) 
ORDER BY Dummy,
  DATETIME_ROW_START,
  DATETIME_ROW_END 