#ifndef TIMEGRANULARITY_H
#define TIMEGRANULARITY_H

enum TIME_GRANULARITY
{

	  TIME_GRANULARITY__START = 0
	, TIME_GRANULARITY__NONE = TIME_GRANULARITY__START
	, TIME_GRANULARITY__SECOND
	, TIME_GRANULARITY__MINUTE
	, TIME_GRANULARITY__HOUR
	, TIME_GRANULARITY__DAY
	, TIME_GRANULARITY__WEEK
	, TIME_GRANULARITY__MONTH
	, TIME_GRANULARITY__QUARTER
	, TIME_GRANULARITY__YEAR
	, TIME_GRANULARITY__BIENNIAL
	, TIME_GRANULARITY__QUADRENNIAL
	, TIME_GRANULARITY__DECADE
	, TIME_GRANULARITY__CENTURY
	, TIME_GRANULARITY__MILLENIUM
	, TIME_GRANULARITY__END

};

#endif
