#ifndef TIMEGRANULARITY_H
#define TIMEGRANULARITY_H

#include <cstdint>

enum TIME_GRANULARITY
{

	  TIME_GRANULARITY__START = 0
	, TIME_GRANULARITY__NONE = 0
	, TIME_GRANULARITY__SECOND = 10
	, TIME_GRANULARITY__MINUTE =20
	, TIME_GRANULARITY__HOUR = 30
	, TIME_GRANULARITY__DAY = 40
	, TIME_GRANULARITY__WEEK = 50
	, TIME_GRANULARITY__MONTH = 60
	, TIME_GRANULARITY__QUARTER = 70
	, TIME_GRANULARITY__YEAR = 80
	, TIME_GRANULARITY__BIENNIAL = 90
	, TIME_GRANULARITY__QUADRENNIAL = 100
	, TIME_GRANULARITY__DECADE = 110
	, TIME_GRANULARITY__CENTURY = 120
	, TIME_GRANULARITY__MILLENIUM = 130
	, TIME_GRANULARITY__END = 131

};

std::int64_t AvgMsperUnit(TIME_GRANULARITY const time_granularity);

#endif
