#include "Setting.h"

SETTING_CATEGORY BackendGlobalSetting::category = SETTING_CATEGORY__GLOBAL_BACKEND;
SETTING_CATEGORY BackendProjectInputSetting::category = SETTING_CATEGORY__PROJECT_INPUT_BACKEND;
SETTING_CATEGORY BackendProjectOutputSetting::category = SETTING_CATEGORY__PROJECT_OUTPUT_BACKEND;
